
[build]
builder = "NIXPACKS"

[env]
PYTHONUNBUFFERED = "1"

[phases.setup]
commands = ["cd backend"]

[phases.build]
commands = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 8000"


[build]
builder = "NIXPACKS"

[env]
NODE_ENV = "production"

[phases.setup]
commands = ["cd frontend"]

[phases.build]
commands = ["npm install", "npm run build"]

[start]
cmd = "npm run start"

web: cd backend && uvicorn main:app --host 0.0.0.0 --port 8000
web: cd frontend && npm run start
